In [1]:
a = [1,2,3,4,5,6,7,8,9,10]

In [3]:
b = []
for i in a:
    b.append(i*5)

In [4]:
b

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [5]:
import numpy as np

In [10]:
%time
a = np.array([1,2,3,4,5,6,7,8,9,10])

Wall time: 0 ns


In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [9]:
a*5 # this was a vectorized operation

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [18]:
numpyArray = np.array([22,33,44.5,55,66,77], dtype="int32") # if one value is float, the entire will become float,
                                                           # same for int32
print(type(numpyArray))
numpyArray

<class 'numpy.ndarray'>


array([22, 33, 44, 55, 66, 77])

In [19]:
numpyArray = np.array([22,33,44.5,55,66,77], dtype=np.int8) # no difference in both conventions
print(type(numpyArray))
numpyArray

<class 'numpy.ndarray'>


array([22, 33, 44, 55, 66, 77], dtype=int8)

In [20]:
randomArray = np.random.randint(10)

In [21]:
randomArray

8

In [22]:
randomArray = np.random.randn(10) # Normal Distribution on numbers

In [23]:
randomArray

array([ 0.47825025, -1.10754658, -0.77029551, -0.1593073 , -0.39544521,
        0.04111342, -1.17043224,  0.29044377,  0.19198368, -1.10702187])

In [24]:
randomArray = np.random.randn(10)*100 # Normal Distribution on numbers, 
                                      # if you want to display in whole numbers, multiply by 10 or 100

In [25]:
randomArray # generates a vector array

array([ 164.42434874,   -6.43827976,   67.9086998 , -213.8905626 ,
        110.80829259, -272.73835438,  -47.34753486, -209.24630462,
          2.13180167, -125.55763422])

In [29]:
randomArray.ndim

1

In [30]:
randomArray.shape # previously specified vector elements shape ka part bangaye hain

(10,)

In [ ]:
array(one dimension)>>> vector
matrix(multi dimensional array) >>> tensor

In [33]:
twoD = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [34]:
twoD

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
twoD.shape

(3, 3)

In [36]:
zeroD = np.array(100) # round bracket shows it is scalar, it will have 0 dimension and empty shape

In [37]:
zeroD.ndim

0

In [38]:
zeroD.shape

()

In [44]:
miscD = np.array([99]) # with one square bracket, it is a vector

In [47]:
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[99]]
2
(1, 1)


In [46]:
miscD = np.array([[99]]) # with 2 square brackets, ek element wala 2D matrix bangaya having one row & one column

In [48]:
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[99]]
2
(1, 1)


In [51]:
miscD = np.array([[[99]]])

In [52]:
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[99]]]
3
(1, 1, 1)


In [55]:
a = np.arange(12).reshape(3,4) # possible combinations for rxc can be 4x3, 2x6 & 6x2 #01

In [56]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
flat = np.ravel(a) # reverting to original shape

In [59]:
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
flat = flat.reshape(12) # second method to revert

In [62]:
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [63]:
z = np.array([22,33,44,55,66,77]) #02

In [64]:
z

array([22, 33, 44, 55, 66, 77])

In [65]:
r = z.reshape(2,3)
r

array([[22, 33, 44],
       [55, 66, 77]])

In [68]:
flat1 = np.ravel(r)

In [69]:
flat1

array([22, 33, 44, 55, 66, 77])

In [90]:
twod = np.arange(36).reshape(6,6) #03

In [91]:
twod

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [92]:
threeD = twod.reshape(3,3,4)

In [93]:
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [94]:
reverting = threeD.reshape(6,6) #reverting using reshape not flat

In [95]:
reverting

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [96]:
#04 manually creating a 3D matrix
threeD = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[7,8,9],[4,5,6],[1,2,3]],[[12,13,14],[15,16,17],[21,31,41]]]) 

In [97]:
threeD

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 7,  8,  9],
        [ 4,  5,  6],
        [ 1,  2,  3]],

       [[12, 13, 14],
        [15, 16, 17],
        [21, 31, 41]]])

In [98]:
threeD.shape

(3, 3, 3)

In [103]:
twod + twod # Mirror arithmetic operations (Shape must be similar)

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46],
       [48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70]])

In [104]:
twod - twod

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [105]:
twod / twod

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [106]:
twod * twod

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [117]:
# In case of shape difference
m1 = np.arange(12).reshape(4,3)

In [118]:
m2 = np.random.randn(9).reshape(3,3) # Shape has to match

In [119]:
m1 + m2

ValueError: operands could not be broadcast together with shapes (4,3) (3,3) 

In [120]:
m3 = np.arange(18).reshape(3,6)
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [122]:
# m3 into m1 nahi hoga cause m3 has 6 col and m1 has 4 rows
# but m1 into m3 is possible cause m1 has 3 col and m3 has 3 rows
# note that the number of elements and shape are different
# output matrix shape is (4,6)
m1@m3

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [123]:
np.dot(m1,m3) # alternative for matrix multiplication

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [124]:
m1.dot(m3) # alternative for matrix multiplication

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [133]:
zeeros = np.zeros((5,5), dtype="int8")

In [134]:
zeeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [135]:
oness = np.ones((5,5), dtype="int32")

In [136]:
oness*50

array([[50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50]])

In [140]:
fulll = np.full((5,5), 25, dtype="int32") 

In [141]:
fulll/5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [144]:
empt = np.empty((4,4,3))

In [145]:
empt # display garbage values stored in the system

array([[[1.06737126e-311, 1.06841732e-311, 5.33590898e-321],
        [1.97626258e-323, 4.28848981e-321, 1.15998375e-028],
        [4.16991405e-321, 8.00801440e+159, 4.74303020e-321],
        [6.01346930e-154, 4.20943930e-321, 6.03109205e-154]],

       [[4.82208070e-321, 6.01391314e-154, 5.19757059e-321],
        [1.17995160e-095, 4.32801506e-321, 1.47898603e-076],
        [5.33590898e-321, 6.01346930e-154, 5.57306049e-321],
        [6.03109205e-154, 5.29638372e-321, 1.03969705e-095]],

       [[5.33590898e-321, 6.01346930e-154, 6.03106471e-154],
        [1.73807132e-076, 8.05431872e-096, 6.03106484e-154],
        [1.81148490e-152, 8.09244594e-153, 8.20680070e-067],
        [1.04006575e-095, 6.03109316e-154, 3.84341244e-057]],

       [[6.01391519e-154, 2.16995743e-076, 8.05801200e-096],
        [4.57670383e-072, 1.79491781e-052, 1.00965617e+141],
        [3.77780862e+180, 1.15998412e-028, 6.48224638e+170],
        [3.67145870e+228, 1.10792167e-047, 5.83289762e-302]]])

In [147]:
like = np.zeros_like(m3) # takes shape and datatype of the argument variable and replicates it with all zeros

In [148]:
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [149]:
like

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [150]:
np.eye(3,3) # identity matrix, jiska diagonal bhi 1 hota hai aur determinant ka answer bhi 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [154]:
i = np.ones(2)

In [157]:
i

array([1., 1.])

In [155]:
j = i.astype("int") # changes datatype

In [156]:
j

array([1, 1])

# Indexing and Slicing

In [158]:
aList = [66,45,67,87]

In [159]:
type(aList)

list

In [160]:
type(aList[2]) #Indexing for a particular value

int

In [161]:
type(aList[0:3]) #Slicing mai datatype doesn't change

list

In [163]:
b1 = aList[0:3] # will display from index 0 till 2, index 3 will be excluded
b1

[66, 45, 67]

In [164]:
tDarray = np.arange(36).reshape(6,6)
tDarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [166]:
tDarray[3,2]

20

In [167]:
tDarray[3][2]

20

In [170]:
# tDarray[row,column]
# tDarray[start:end, start:end]
b2 = tDarray[2:5,1:4]
b2

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [173]:
b3 = tDarray[5:,3:4]

In [176]:
b3
type(b3)

numpy.ndarray

In [175]:
b4 = tDarray[1:2,2:5 ]
b4

array([[ 8,  9, 10]])