In [10]:
import numpy as np

In [11]:
miscD = np.array([[99]]) # with one square bracket, it is a vector

In [12]:
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[99]]
2
(1, 1)


In [28]:
arr1d= np.array([33,24,56,74,75])

In [29]:
arr1d[-1]

75

In [30]:
arr1d[-2]

74

In [18]:
arr2d = np.array([[2,3,4], [5,6,7], [8,9,0]])

In [19]:
arr2d

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 0]])

In [20]:
arr2d[0]

array([2, 3, 4])

In [21]:
arr2d[0,0]

2

In [26]:
arr2d[1:,1:]

array([[6, 7],
       [9, 0]])

In [27]:
arr2d[:2,1:]

array([[3, 4],
       [6, 7]])

In [37]:
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]],[[111,222,333],[444,555,666],[777,888,999]]])

In [38]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  22,  33],
        [ 44,  55,  66],
        [ 77,  88,  99]],

       [[111, 222, 333],
        [444, 555, 666],
        [777, 888, 999]]])

In [39]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr3d[0,1]

array([4, 5, 6])

In [41]:
arr3d[0,1,0]

4

In [42]:
arr3d.shape

(3, 3, 3)

In [47]:
arr3d[1:2, 0:2,0: ]

array([[[11, 22, 33],
        [44, 55, 66]]])

In [43]:
tDarray = np.arange(36).reshape(3,2,6)

In [44]:
tDarray

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [45]:
tDarray[1,0,3]

15

In [48]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  22,  33],
        [ 44,  55,  66],
        [ 77,  88,  99]],

       [[111, 222, 333],
        [444, 555, 666],
        [777, 888, 999]]])

In [50]:
arr3d[0, 0:2,1: ] # first argument mai 0 ke baad : ki need nahi hai, it is understood that it will start from the 0th index

array([[2, 3],
       [5, 6]])

In [51]:
arrtwo = np.array([[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[6,6,1,5,3],[7,5,1,6,5],[8,2,4,9,7]])

In [52]:
arrtwo

array([[ 2,  4,  6,  8, 10],
       [ 1,  2,  3,  4,  5],
       [ 4,  0,  6,  2,  5],
       [ 6,  6,  1,  5,  3],
       [ 7,  5,  1,  6,  5],
       [ 8,  2,  4,  9,  7]])

In [56]:
arrtwo[2:4,1:4]

array([[0, 6, 2],
       [6, 1, 5]])

In [60]:
tDarraytwo = np.arange(1,37).reshape(6,6) # specified starting element and (ending+1) element

In [61]:
tDarraytwo

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [62]:
tDarraytwo[2:4,2:5]

array([[15, 16, 17],
       [21, 22, 23]])

In [66]:
tDarraytwo[2:3]

array([[13, 14, 15, 16, 17, 18]])

In [67]:
tDarraytwo[2:3,0:6]

array([[13, 14, 15, 16, 17, 18]])

In [73]:
tDarraytwo[4:5,:] # khaali colon means all rows, 
                  # empty, no comma and not even ending row specified gives the same result

array([[25, 26, 27, 28, 29, 30]])

In [74]:
tDarraytwo[4,4] # indexing

29

In [86]:
tDarraytwo[,2] # will give error, the case is not same for column convention

SyntaxError: invalid syntax (<ipython-input-86-1ca5dcca9687>, line 1)

In [87]:
tDarraytwo[:, 2] # picked the entire column and displayed it like a row

array([ 3,  9, 15, 21, 27, 33])

In [78]:
tDarraytwo[1:5,]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [85]:
tDarraytwo

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [83]:
tDarraytwo[2:4,5] # displays it like a vector

array([18, 24])

In [88]:
tDarraytwo[2:4,5:] # displays it like a 2D array, it is a 2 dimensional slice

array([[18],
       [24]])

In [84]:
tDarraytwo[2:4,-1]

array([18, 24])

In [82]:
tDarraytwo[2:4,:5] # selected all columns except the Fifth column, picked 0th,1st,2nd,3rd,4th columns

array([[13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23]])

In [94]:
tDarraytwo[:,::-1]

array([[ 6,  5,  4,  3,  2,  1],
       [12, 11, 10,  9,  8,  7],
       [18, 17, 16, 15, 14, 13],
       [24, 23, 22, 21, 20, 19],
       [30, 29, 28, 27, 26, 25],
       [36, 35, 34, 33, 32, 31]])

In [91]:
tDarraytwo[:,:2]

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [92]:
tDarraytwo[:,::2] # :2 is for step

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [93]:
tDarraytwo[:,::-2]

array([[ 6,  4,  2],
       [12, 10,  8],
       [18, 16, 14],
       [24, 22, 20],
       [30, 28, 26],
       [36, 34, 32]])

In [95]:
tDarraytwo[::2,:]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18],
       [25, 26, 27, 28, 29, 30]])

# Boolean Indexing

In [96]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [97]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [98]:
data = np.random.randn(7, 4)

In [99]:
data

array([[-0.34011265, -0.30100274,  1.2374008 ,  0.72526601],
       [-2.38484234,  0.85585636,  0.2920307 , -1.0291611 ],
       [-0.6456353 , -1.62911652,  0.28952128, -0.76365186],
       [ 0.1567353 ,  1.21891927, -0.4920199 ,  0.14188898],
       [-0.01082537, -0.72060963,  1.83984416, -0.46592766],
       [ 1.10046709,  1.08059113,  0.26830481, -0.26629864],
       [ 0.40081124, -0.16275516,  0.71943515,  1.19150215]])

In [107]:
names == "Bob" # string matching with array

array([ True, False, False,  True, False, False, False])

In [108]:
names[names == "Bob"]

array(['Bob', 'Bob'], dtype='<U4')

In [109]:
data>1

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [ True,  True, False, False],
       [False, False, False,  True]])

In [104]:
data[data>1] # storing exact values in data's own frame, instead of displaying True&False, it displays those exact elements

array([1.2374008 , 1.21891927, 1.83984416, 1.10046709, 1.08059113,
       1.19150215])

In [110]:
data[names=="Bob"]

array([[-0.34011265, -0.30100274,  1.2374008 ,  0.72526601],
       [ 0.1567353 ,  1.21891927, -0.4920199 ,  0.14188898]])

In [111]:
data[names=="Joe"]

array([[-2.38484234,  0.85585636,  0.2920307 , -1.0291611 ],
       [ 1.10046709,  1.08059113,  0.26830481, -0.26629864],
       [ 0.40081124, -0.16275516,  0.71943515,  1.19150215]])

In [112]:
bol = [True, False, False, False, False, True, False]

In [113]:
data[bol]

array([[-0.34011265, -0.30100274,  1.2374008 ,  0.72526601],
       [ 1.10046709,  1.08059113,  0.26830481, -0.26629864]])

In [115]:
data

array([[-0.34011265, -0.30100274,  1.2374008 ,  0.72526601],
       [-2.38484234,  0.85585636,  0.2920307 , -1.0291611 ],
       [-0.6456353 , -1.62911652,  0.28952128, -0.76365186],
       [ 0.1567353 ,  1.21891927, -0.4920199 ,  0.14188898],
       [-0.01082537, -0.72060963,  1.83984416, -0.46592766],
       [ 1.10046709,  1.08059113,  0.26830481, -0.26629864],
       [ 0.40081124, -0.16275516,  0.71943515,  1.19150215]])

In [114]:
data[names!="Bob"]

array([[-2.38484234,  0.85585636,  0.2920307 , -1.0291611 ],
       [-0.6456353 , -1.62911652,  0.28952128, -0.76365186],
       [-0.01082537, -0.72060963,  1.83984416, -0.46592766],
       [ 1.10046709,  1.08059113,  0.26830481, -0.26629864],
       [ 0.40081124, -0.16275516,  0.71943515,  1.19150215]])

In [116]:
cond = names != "Bob"

In [117]:
data[cond]

array([[-2.38484234,  0.85585636,  0.2920307 , -1.0291611 ],
       [-0.6456353 , -1.62911652,  0.28952128, -0.76365186],
       [-0.01082537, -0.72060963,  1.83984416, -0.46592766],
       [ 1.10046709,  1.08059113,  0.26830481, -0.26629864],
       [ 0.40081124, -0.16275516,  0.71943515,  1.19150215]])

In [118]:
data[~cond]

array([[-0.34011265, -0.30100274,  1.2374008 ,  0.72526601],
       [ 0.1567353 ,  1.21891927, -0.4920199 ,  0.14188898]])

In [119]:
data[~cond,3]

array([0.72526601, 0.14188898])

In [123]:
data[cond,2: ]

array([[ 0.2920307 , -1.0291611 ],
       [ 0.28952128, -0.76365186],
       [ 1.83984416, -0.46592766],
       [ 0.26830481, -0.26629864],
       [ 0.71943515,  1.19150215]])

In [129]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [133]:
# cond = names != "Bob"
data = np.arange(1,29).reshape(7,4)
print(data)
print(cond)
data[cond,1:3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]]
[False  True  True False  True  True  True]


array([[ 6,  7],
       [10, 11],
       [18, 19],
       [22, 23],
       [26, 27]])

In [134]:
cond = (names == "Bob") | (names == "Joe")

In [135]:
cond

array([ True,  True, False,  True, False,  True,  True])

In [136]:
data[cond]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [13, 14, 15, 16],
       [21, 22, 23, 24],
       [25, 26, 27, 28]])

In [137]:
arr = np.empty((8, 4))

In [138]:
arr

array([[1.13571458e-153, 2.18174368e+243, 5.84938530e+199,
        5.63096753e+175],
       [1.27734658e-152, 3.99524045e+252, 6.01334659e-154,
        3.17095803e+180],
       [3.03181047e+180, 9.05280211e+223, 2.61261355e+257,
        2.30224756e+161],
       [2.44832746e+198, 7.62870703e+228, 6.21813868e+175,
        1.38760003e+219],
       [6.01347002e-154, 1.09996094e+155, 8.88759996e+252,
        2.45943181e+198],
       [4.61486429e+281, 6.01346953e-154, 3.28598439e+161,
        1.03819125e-028],
       [3.53385238e+246, 4.96042068e+180, 1.94207473e+227,
        7.35423706e+223],
       [9.77824555e+199, 6.01334653e-154, 5.81948471e+199,
        2.15754767e+185]])

In [139]:
for i in range(8):
    arr[i] = i

In [140]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [142]:
arr[[4,7,1]] # fancy indexing means row order is given by you

array([[4., 4., 4., 4.],
       [7., 7., 7., 7.],
       [1., 1., 1., 1.]])

In [150]:
arr[[4,7,1,4],[3,0,2,1]] # First square bracket specifies row number and second bracket specifies element number
# (4,3),(7,0),(1,2),(4,1)

array([4., 7., 1., 4.])

In [155]:
arr1 = np.arange(32).reshape(8,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [154]:
arr1[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

# 1[0,3,1,2], 5[0,3,1,2], 7[0,3,1,2], 2[0,3,1,2]

# ([[(1,0),(1,3),(1,1),(1,2),
# (5,0),(5,3),(5,1),(5,2),
# (7,0),(7,3),(7,1),(7,2),
# (2,0),(2,3),(2,1),(2,2)]])

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [156]:
arr1.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [166]:
t = arr1.T
t

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

# Concatenation

In [158]:
arrr1 = np.array([[1,2,3],[4,5,6]])
arrr1

array([[1, 2, 3],
       [4, 5, 6]])

In [159]:
arrr2 = np.array([[7,8,9],[11,22,33]])
arrr2

array([[ 7,  8,  9],
       [11, 22, 33]])

In [164]:
np.concatenate([arrr1,arrr2],axis=0) # vertical concatenation hui hai but no. of rows increased so axis is 0 means row
                                     # by default axis 0 pe concatenation hoti hai

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 22, 33]])

In [165]:
np.concatenate([arrr1,arrr2],axis=1) # horizontal concatenation but no. of columns increased hence axis will be ONE(column)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 11, 22, 33]])

In [168]:
stc = np.stack([arrr1,arrr2])

In [169]:
stc

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 22, 33]]])

In [170]:
stc.shape

(2, 2, 3)

In [171]:
stc.ndim

3

In [172]:
np.vstack([arrr1,arrr2]) # v ---> vertical

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 22, 33]])

In [173]:
np.hstack([arrr1,arrr2]) # h ---> horizontal

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 11, 22, 33]])

In [178]:
arr = np.arange(36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [179]:
np.vsplit(arr,3) # vertical split mai horizontally breakdown hoga

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [181]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [180]:
np.hsplit(arr,3) # horizontal split mai vertically breakdown hoga

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]