In [1]:
# a.
import numpy as np

In [3]:
# b.
arrzero = np.zeros(24).reshape(2,3,4)

In [4]:
arrzero

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [5]:
# c.
arrone = np.ones(24).reshape(2,3,4)
arrone

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [6]:
# d.
arr = np.arange(1000)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [66]:
# e.
list1 = [2,3.2,5.5,-6.4,-2.2,2.4]
list1
print(max(list1))
print(min(list1))

5.5
-6.4


In [15]:
a = np.array(list1)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[ 2.   3.2  5.5 -6.4 -2.2  2.4]


In [16]:
# f.
a[1]

3.2

In [17]:
# g.
a[1:4]

array([ 3.2,  5.5, -6.4])

In [18]:
a = np.array([[2,3.2,5.5,-6.4,-2.2,2.4],[1,22,4,0.1,5.3,-9],[3,1,2.1,21,1.1,-2]])

In [19]:
a

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [28]:
print(type(a))
print(a.shape)
print(a.ndim)

<class 'numpy.ndarray'>
(3, 6)
2


In [42]:
a[:,:3] # saari rows, starting column se 2nd indexed column tak

array([[ 2. ,  3.2,  5.5],
       [ 1. , 22. ,  4. ],
       [ 3. ,  1. ,  2.1]])

In [43]:
a[:,3] # printing column 3

array([-6.4,  0.1, 21. ])

In [44]:
 a[1:4,0:4] # thing to notice here is that it does not throw error for row's
            # out of bound index (i.e. 4) and same goes for column

array([[ 1. , 22. ,  4. ,  0.1],
       [ 3. ,  1. ,  2.1, 21. ]])

In [45]:
a[1:,2]

array([4. , 2.1])

In [48]:
# h.
arr = np.arange(10,14).reshape(2,4)
arr

array([[10, 11],
       [12, 13]])

In [71]:
arr1 = np.array([[0,1,2,3],[10,11,13,14]])
print(arr1)
print(arr1.shape)
print(arr1.size)
print(np.amax(arr1))
print(np.amin(arr1))

[[ 0  1  2  3]
 [10 11 13 14]]
(2, 4)
8
14
0


# Alternative method

In [69]:
a = np.array([[0,1,2,3]])
b = np.array([[10,12,13,14]])
arr = np.concatenate((a,b), axis=0)
print(arr)
print(arr.shape)
print(arr.size)
print(np.amax(arr))
print(np.amin(arr))

[[ 0  1  2  3]
 [10 12 13 14]]
(2, 4)
8
14
0


In [79]:
arr2 = arr.reshape(2,2,2)
arr2

array([[[ 0,  1],
        [ 2,  3]],

       [[10, 12],
        [13, 14]]])

In [73]:
arr2.transpose()

array([[[ 0, 10],
        [ 2, 13]],

       [[ 1, 12],
        [ 3, 14]]])

In [74]:
flat = np.ravel(arr2)

In [75]:
flat

array([ 0,  1,  2,  3, 10, 12, 13, 14])

In [80]:
flat = np.array(flat, dtype="float32")

In [81]:
flat

array([ 0.,  1.,  2.,  3., 10., 12., 13., 14.], dtype=float32)

In [82]:
arr2 = np.array(arr2, dtype="float64")
arr2

array([[[ 0.,  1.],
        [ 2.,  3.]],

       [[10., 12.],
        [13., 14.]]])

In [84]:
oneD = np.arange(1,21)
oneD

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [85]:
abc = np.arange(1,10)
abc1 = abc*3
abc1

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [107]:
rando = np.random.uniform(0,1)

In [108]:
rando

0.992630647450228

In [111]:
x = np.random.rand(8)
x

array([0.84703297, 0.6007579 , 0.90346607, 0.33438222, 0.67056347,
       0.61504033, 0.52195664, 0.15586907])

In [115]:
A = np.array([[1,2,3,4],[5,6,7,8]])
A
#A = np.reshape()

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [117]:
A1 = [1,2,3,4]
A2 = [5,6,7,8]
A = np.concatenate((A1,A2), axis = 0)
A

array([1, 2, 3, 4, 5, 6, 7, 8])

In [127]:
A = np.arange(1,9).reshape(2,4)
print(A)
print(A.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [128]:
B = np.array([[1, 2]])
print(B)
print(B.shape)

[[1 2]]
(1, 2)


In [130]:
B,A = np.broadcast_arrays(B,A)

ValueError: shape mismatch: objects cannot be broadcast to a single shape